apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-site-deployment
  labels:
    app: portfolio-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-site
  template:
    metadata:
      labels:
        app: portfolio-site
    spec:
      containers:
        - name: portfolio-site-container
          image: portfolio-site
          imagePullPolicy: Never
          ports:
            - containerPort: 80