apiVersion: v1
kind: Service
metadata:
  name: portfolio-site-service
spec:
  type: LoadBalancer
  selector:
    app: portfolio-site
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
